name: Push File(or Dir) to another repository

on:
  push:
    branches: [main]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
          uses: actions/checkout@v2
          env:
            SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          with:
            source-directory: 'build/'
            destination-github-username: 'Vverma-27'
            destination-repository-name: 'Kalyan-backend'
            user-email: 'vverma270705@gmail.com'
            commit-message: 'Build transferred automatically'
            target-branch: main
      - run: npm build